package dev.hostapp.backend.service;

import dev.hostapp.backend.model.Server;
import dev.hostapp.backend.model.User;
import dev.hostapp.backend.repository.DeviceRepository;
import dev.hostapp.backend.repository.ServerRepository;
import dev.hostapp.backend.repository.ServerRequestRepository;
import dev.hostapp.backend.repository.UserRepository;
import jakarta.transaction.Transactional;
import org.springframework.boot.ApplicationArguments;
import org.springframework.boot.ApplicationRunner;
import org.springframework.stereotype.Component;

import java.util.LinkedHashSet;
import java.util.Set;

/** Removes accounts generated by the former demo seeder, including their data. */
@Component
public class DemoDataCleanup implements ApplicationRunner {
    private final UserRepository users;
    private final DeviceRepository devices;
    private final ServerRequestRepository requests;
    private final ServerRepository servers;
    private final ServerRequestService requestService;

    public DemoDataCleanup(UserRepository users, DeviceRepository devices,
                           ServerRequestRepository requests, ServerRepository servers,
                           ServerRequestService requestService) {
        this.users = users;
        this.devices = devices;
        this.requests = requests;
        this.servers = servers;
        this.requestService = requestService;
    }

    @Override
    @Transactional
    public void run(ApplicationArguments args) {
        Set<Server> demoServers = new LinkedHashSet<>();
        for (int i = 1; i <= 5; i++) {
            User user = users.findByEmail("demo" + i + "@hostapp.local").orElse(null);
            if (user == null || !"Demo".equals(user.getName())
                    || !("User " + i).equals(user.getSurname())) {
                continue;
            }
            for (var request : requests.findAllByOwner(user)) {
                if (request.getServer() != null) {
                    demoServers.add(request.getServer());
                }
                requestService.delete(request.getId(), user, true);
            }
            devices.deleteAllByUser(user);
            users.delete(user);
        }
        requests.flush();
        for (Server server : demoServers) {
            if (!requests.existsByServer_Id(server.getId())) {
                servers.delete(server);
            }
        }
    }
}
